apiVersion: v1
kind: Service
metadata:
  name: firefox-service
spec:
  selector:
    app: firefox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Should match the container port from the deployment
  type: LoadBalancer # You can use NodePort or ClusterIP depending on your setup

